"""empty message

Revision ID: efbd1386ab19
Revises: 67ceba604b8f
Create Date: 2021-04-15 05:31:03.890764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efbd1386ab19'
down_revision = '67ceba604b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ordenes', sa.Column('event_address', sa.String(length=512), nullable=True))
    op.add_column('ordenes', sa.Column('event_date', sa.String(length=250), nullable=True))
    op.add_column('service', sa.Column('precio', sa.Integer(), nullable=True))
    op.drop_column('service', 'costo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('costo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('service', 'precio')
    op.drop_column('ordenes', 'event_date')
    op.drop_column('ordenes', 'event_address')
    op.drop_table('shop_cart')
    # ### end Alembic commands ###
